---
- name: Creating RDS Subnet groups
  rds_subnet_group:
    state: present
    name: "{{rds_group_name}}"
    description: "{{rds_group_description}}"
    region: "{{region}}"
    subnets:
      - "{{ vpc_info.db1_subnet.subnet.id }}" 
      - "{{ vpc_info.db2_subnet.subnet.id }}"     
 