---
- hosts: local
  name: Creating app routetable
  vars_prompt:
    - name: "rt1_name"
      prompt: "Enter the name of the routetable"
      private: no
    - name: "destination1"
      prompt: "Enter the destination of the routetable"
      private: no

  tasks:
    - name: Creating app routetable
      include_role: 
        name: ../roles/routetable
      vars:
        rt_name: "{{rt1_name}}"
        destination: "{{destination1}}"
        subnet1_id: "{{ vpc_info.app1_subnet.subnet.id }}"
        subnet2_id: "{{ vpc_info.app2_subnet.subnet.id }}" 
        gateway_id: "{{ new_nat_gateway.nat_gateway_id }}" 
    - name: Print output
      debug: 
        var: vpc_info
