---
- hosts: local
  name: Creating app server 2 subnet
  vars_prompt:
    - name: "cidr_block_subnet4"
      prompt: "Enter the CIDR block you want for app server 2 subnet"
      private: no
    - name: "subnet_name4"
      prompt: "Enter the name of the app server 2 subnet"
      private: no
    - name: "subnet_env4"
      prompt: "Enter the environment tag of app server 2 subnet"
      private: no
    - name: "subnet_az4"
      prompt: "Enter the availability zone of app server 2 subnet"
      private: no

  tasks:
    - name: Creating app server 2 subnet
      include_role: 
        name: ../roles/subnet
      vars:
        cidr_block: "{{cidr_block_subnet4}}"
        subnet_name: "{{subnet_name4}}"
        subnet_env: "{{subnet_env4}}"
        subnet_az: "{{subnet_az4}}"
        subnet_key: app2_subnet
    - name: Print output
      debug: 
        var: vpc_info
