---
- hosts: local
  name: Creating app server 1 subnet
  vars_prompt:
    - name: "cidr_block_subnet3"
      prompt: "Enter the CIDR block you want for app server 1 subnet"
      private: no
    - name: "subnet_name3"
      prompt: "Enter the name of the app server 1 subnet"
      private: no
    - name: "subnet_env3"
      prompt: "Enter the environment tag of app server 1 subnet"
      private: no
    - name: "subnet_az3"
      prompt: "Enter the availability zone of app server 1 subnet"
      private: no

  tasks:
    - name: Creating app server 1 subnet
      include_role: 
        name: ../roles/subnet
      vars:
        cidr_block: "{{cidr_block_subnet3}}"
        subnet_name: "{{subnet_name3}}"
        subnet_env: "{{subnet_env3}}"
        subnet_az: "{{subnet_az3}}"
        subnet_key: app1_subnet
    - name: Print output
      debug: 
        var: vpc_info
