---
- hosts: local
  name: Creating db routetable
  vars_prompt:
    - name: "rt2_name"
      prompt: "Enter the name of the routetable"
      private: no
    - name: "destination2"
      prompt: "Enter the destination of the routetable"
      private: no

  tasks:
    - name: Creating db routetable
      include_role: 
        name: ../roles/routetable
      vars:
        rt_name: "{{rt2_name}}"
        destination: "{{destination2}}"
        subnet1_id: "{{ vpc_info.db1_subnet.subnet.id }}"
        subnet2_id: "{{ vpc_info.db2_subnet.subnet.id }}" 
        gateway_id: "{{ new_nat_gateway.nat_gateway_id }}" 
    - name: Print output
      debug: 
        var: vpc_info
