---
- hosts: local
  vars_prompt:
    - name: "db_sg_name"
      prompt: "Enter the name of the security group for database layer"
      private: no
    - name: "db_sg_desc"
      prompt: "Enter the description of the security group for database layer"
      private: no
    - name: "db_sg_rule_desc"
      prompt: "Enter the rule description for database layer "
      private: no
    - name: "db_protocol"
      prompt: "Enter the protocol for database layer "
      private: no
    - name: "db_port_no"
      prompt: "Enter the port number for database layer "
      private: no
    - name: "db_source_cidr"
      prompt: "Enter the source CIDR block for database layer "
      private: no

  tasks:
    - set_fact:
         db_sg_name: "{{db_sg_name}}"
         db_sg_desc: "{{db_sg_desc}}"
         db_sg_rule_desc: "{{db_sg_rule_desc}}"
         db_protocol: "{{db_protocol}}"
         db_port_no: "{{db_port_no}}"
         db_source_cidr: "{{db_source_cidr}}"
         
  
  roles:
     - ../roles/db_security_group