---
- hosts: local
  vars_prompt:
    - name: "instance_name4"
      prompt: "Enter the name of the app server 2"
      private: no
    - name: "ec2_type4"
      prompt: "Enter the type of instance you want "
      private: no
    - name: "sg4"
      prompt: "Enter the name of the security group"
      private: no
    - name: "public_ip4"
      prompt: "Do you want public IP for app server 2"
      private: no
    - name: "ec2_image4"
      prompt: "Enter image of your EC2 instance"
      private: no 

  tasks:
    - name: Creating app server 2
      include_role: 
        name: ../roles/ec2
      vars:
        instance_name: "{{instance_name4}}"
        ec2_type: "{{ec2_type4}}"
        sg: "{{sg4}}"
        public_ip: "{{public_ip4}}"
        ec2_subnet_id: "{{ vpc_info.app2_subnet.subnet.id }}"
        ec2_name: appserver2
        ec2_image: "{{ec2_image4}}"
    - name: Print output
      debug: 
        var: vpc_info