---
- hosts: local
  name: Creating lb server 1 subnet
  vars_prompt:
    - name: "cidr_block_subnet7"
      prompt: "Enter the CIDR block you want for lb server 1 subnet"
      private: no
    - name: "subnet_name7"
      prompt: "Enter the name of the lb server 1 subnet"
      private: no
    - name: "subnet_env7"
      prompt: "Enter the environment tag of lb server 1 subnet"
      private: no
    - name: "subnet_az7"
      prompt: "Enter the availability zone of lb server 1 subnet"
      private: no

  tasks:
    - name: Creating lb server 1 subnet
      include_role: 
        name: ../roles/subnet
      vars:
        cidr_block: "{{cidr_block_subnet7}}"
        subnet_name: "{{subnet_name7}}"
        subnet_env: "{{subnet_env7}}"
        subnet_az: "{{subnet_az7}}"
        subnet_key: lb1_subnet
    - name: Print output
      debug: 
        var: vpc_info
