---
- hosts: local
  vars_prompt:
    - name: "rds_group_name"
      prompt: "Enter the name of the RDS subnet group"
      private: no
    - name: "rds_group_description"
      prompt: "Enter the description of the group"
      private: no
  tasks:
    - set_fact:
        rds_group_name: "{{rds_group_name}}"
        rds_group_description: "{{rds_group_description}}"
  roles:
     - ../roles/rds_subnet_group