---
- import_playbook : webserver1_subnet.yml
- import_playbook : lb1_subnet.yml
- import_playbook : webserver2_subnet.yml
- import_playbook : lb2_subnet.yml
- import_playbook : appserver1_subnet.yml
- import_playbook : appserver2_subnet.yml
- import_playbook : db1_subnet.yml
- import_playbook : db2_subnet.yml